---
apiVersion: v1
kind: Service
metadata:
  name: news-demo
  namespace: news-demo
  labels:
    app: news-demo
spec:
  selector:
    app: news-demo
  ports:
    - port: 3000
      targetPort: 3000
  type: NodePort
